server:
  port: 8085
  address: 0.0.0.0

spring:
  application:
    name: batchProcessing

  datasource:
    url: jdbc:postgresql://localhost:5432/batch_processing
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

    hikari:
      auto-commit: false

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  batch:
    job:
      enabled: false

otp:
  length: 6         # Length of OTP
  alphanumeric: false # true for alphanumeric, false for numeric
  expiryInSeconds: 300 # OTP expiry time in seconds (5 minutes)

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /v1/swagger